### ISSUE TITLE
Fails to compile on Arch Linux kernel version 6.18.7-arch1-1

### ISSUE THREAD

**Issue by shadow-absorber** [0xsirus/tirdad#30]
here is the make commands output:
```
KERNELDIR: /lib/modules/6.18.7-arch1-1/build
cd module; make -C /lib/modules/6.18.7-arch1-1/build M=/home/user/git/tirdad/module
make[1]: Entering directory '/usr/lib/modules/6.18.7-arch1-1/build'
make[2]: Entering directory '/home/user/git/tirdad/module'
  CC [M]  tirdad.o
tirdad.c:67:24: error: array type has incomplete element type ‘struct klp_func’
   67 | static struct klp_func funcs[] = {
      |                        ^~~~~
tirdad.c:78:26: error: array type has incomplete element type ‘struct klp_object’
   78 | static struct klp_object objs[] = {
      |                          ^~~~
tirdad.c:84:15: error: variable ‘patch’ has initializer but incomplete type
   84 | static struct klp_patch patch = {
      |               ^~~~~~~~~
tirdad.c:85:10: error: ‘struct klp_patch’ has no member named ‘mod’
   85 |         .mod = THIS_MODULE,
      |          ^~~
In file included from tirdad.c:8:
/usr/lib/modules/6.18.7-arch1-1/build/include/linux/init.h:174:21: warning: excess elements in struct initializer
  174 | #define THIS_MODULE (&__this_module)
      |                     ^
tirdad.c:85:16: note: in expansion of macro ‘THIS_MODULE’
   85 |         .mod = THIS_MODULE,
      |                ^~~~~~~~~~~
/usr/lib/modules/6.18.7-arch1-1/build/include/linux/init.h:174:21: note: (near initialization for ‘patch’)
  174 | #define THIS_MODULE (&__this_module)
      |                     ^
tirdad.c:85:16: note: in expansion of macro ‘THIS_MODULE’
   85 |         .mod = THIS_MODULE,
      |                ^~~~~~~~~~~
tirdad.c:86:10: error: ‘struct klp_patch’ has no member named ‘objs’
   86 |         .objs = objs,
      |          ^~~~
tirdad.c:86:17: warning: excess elements in struct initializer
   86 |         .objs = objs,
      |                 ^~~~
tirdad.c:86:17: note: (near initialization for ‘patch’)
tirdad.c: In function ‘hook_init’:
tirdad.c:118:16: error: implicit declaration of function ‘klp_enable_patch’ [-Wimplicit-function-declaration]
  118 |         return klp_enable_patch(&patch);
      |                ^~~~~~~~~~~~~~~~
tirdad.c: At top level:
tirdad.c:84:25: error: storage size of ‘patch’ isn’t known
   84 | static struct klp_patch patch = {
      |                         ^~~~~
tirdad.c:78:26: warning: ‘objs’ defined but not used [-Wunused-variable]
   78 | static struct klp_object objs[] = {
      |                          ^~~~
tirdad.c:67:24: warning: ‘funcs’ defined but not used [-Wunused-variable]
   67 | static struct klp_func funcs[] = {
      |                        ^~~~~
make[4]: *** [/usr/lib/modules/6.18.7-arch1-1/build/scripts/Makefile.build:287: tirdad.o] Error 1
make[3]: *** [/usr/lib/modules/6.18.7-arch1-1/build/Makefile:2010: .] Error 2
make[2]: *** [/usr/lib/modules/6.18.7-arch1-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/home/user/git/tirdad/module'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.18.7-arch1-1/build'
make: *** [Makefile:12: all] Error 2
```
hope this helps and that you can instruct shadow how to fix this to be able to use tirdad

**Comment by shadow-absorber** [comment]
> > Do you have /proc/config.gz ? If yes run zgrep CONFIG_LIVEPATCH /proc/config.gz 
 ```
 $ zgrep CONFIG_LIVEPATCH /proc/config.gz
 # CONFIG_LIVEPATCH is not set
 ```

**Comment by 0xsirus** [comment]
Your kernel wasn't compiled with live patch support which is necessary to run this version of `tirdad`. If this is a default arch install, you either need to compile the kernel yourself or use another distro.

@adrelanos @arraybolt3 it's likely that live patching is going to be disabled by default in newer kernels. Still Debian trixie is fine. But heads up on this.
I noticed the config variable is not by default enabled in 6.19. I manually enabled it and compiled the kernel to test, and can verify the module builds and loads normally. But the module cannot be removed anymore by `rmmod`. First, user has to disable the patch manually through `/sys/kernel/`  which is easy (`echo 0 > /sys/kernel/livepatch/tiradad/enabled`) but inconvenient. Therefore, for turning off `tirdad` you need a user-space wrapper. It seems to be an intentional limitation recently added to kernel design. Overall, as I expected, switching to this native patching feature is not as hassle-free as it looks to be. Still much better than hacking the page tables but let's hope it stays on by default on Debian stable kernels.

**Comment by shadow-absorber** [comment]
> Your kernel wasn't compiled with live patch support which is necessary to run this version of `tirdad`. If this is a default arch install, you either need to compile the kernel yourself or use another distro.
> 
> [@adrelanos](https://github.com/adrelanos) [@ArrayBolt3](https://github.com/ArrayBolt3) it's likely that live patching is going to be disabled by default in newer kernels. Still Debian trixie is fine. But heads up on this. I noticed the config variable is not by default enabled in 6.19. I manually enabled it and compiled the kernel to test, and can verify the module builds and loads normally. But the module cannot be removed anymore by `rmmod`. First, user has to disable the patch manually through `/sys/kernel/` which is easy (`echo 0 > /sys/kernel/livepatch/tiradad/enabled`) but inconvenient. Therefore, for turning off `tirdad` you need a user-space wrapper. It seems to be an intentional limitation recently added to kernel design. Overall, as I expected, switching to this native patching feature is not as hassle-free as it looks to be. Still much better than hacking the page tables but let's hope it stays on by default on Debian stable kernels.

thanks for helping shadow figure out the cause.. this is indeed the default arch linux kernel
guess next weekend is gonna be figure out how to compile linux kernel to mess with patches and flags

**Comment by 0xsirus** [comment]
Sounds good. I'm haven't looked into the commits behind these configuration changes and hence not aware of the details, but generally they try to make it difficult to touch kernel memory even through a legitimate functionality. So they might say if someone needs to patch/debug kernel functions, they need to compile the kernel themselves. Regardless I agree that we need to raise an issue if the support is dropped in Debian as this is quite a useful feature. Let's keep an eye and see what happens there.

Closing this issue as the module compiles and works normally in the latest stable Debian release.
